apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: borges-producer
spec:
  template:
    metadata:
      labels:
        app: borges-producer
    spec:
      containers:
      - name: borges
        image: quay.io/srcd/borges:v0.6.6
        command: ['borges','producer','--mentionsqueue=rovers']
        env:
        - name: CONFIG_BROKER
          value: 'amqp://guest:guest@rabbitmq:5672'
        - name: CONFIG_DBUSER
          value: testing
        - name: CONFIG_DBPASS
          value: testing
        - name: CONFIG_DBHOST
          value: postgres
        - name: CONFIG_DBNAME
          value: testing
      imagePullSecrets:
      - name: quay
#      nodeSelector:
#        kubernetes.io/hostname: ""