[[constraint]]
  name = "github.com/inconshreveable/log15"
  version = "2.11.0"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/satori/go.uuid"

[[constraint]]
  name = "gopkg.in/src-d/core-retrieval.v0"
  source = "https://github.com/src-d/core-retrieval.git"

[[constraint]]
  branch = "master"
  name = "gopkg.in/src-d/framework.v0"

[[constraint]]
  name = "gopkg.in/src-d/go-billy.v4"
  source = "https://github.com/src-d/go-billy.git"

[[constraint]]
  name = "gopkg.in/src-d/go-errors.v0"
  version = "0.1.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git-fixtures.v3"
  version = "3.1.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  source = "https://github.com/src-d/go-git.git"
  version = "4.2.0"

[[constraint]]
  name = "gopkg.in/src-d/go-kallax.v1"
  version = "1.3.3"
